name: farida

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  staging-deployment:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'

    - name: Install Dependencies
      run: npm install --force

    - name: Build Angular App
      run: npm run build

    - name: Create .htaccess
      run: |
        echo "RewriteEngine On" > dist/e-learning/.htaccess
        echo "RewriteBase /" >> dist/e-learning/.htaccess
        echo "RewriteRule ^index\.html$ - [L]" >> dist/e-learning/.htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-f" >> dist/e-learning/.htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-d" >> dist/e-learning/.htaccess
        echo "RewriteRule . index.html [L]" >> dist/e-learning/.htaccess

    - name: Upload build to temporary deploy folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_NODE_1 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "dist/e-learning/*"
        target: "/var/www/html/steps-front-deploying"

    - name: Finalize deployment (backup & switch folders)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_NODE_1 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Make backup of current app if it exists
          if [ -d "/var/www/html/steps-front" ]; then
            rm -rf /var/www/html/steps-front-backup
            mv /var/www/html/steps-front /var/www/html/steps-front-backup
          fi

          # Move the new build into place
          mv /var/www/html/steps-front-deploying /var/www/html/steps-front

    - name: Discord Notification
      if: ${{ success() }}
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: ':green_circle: The project **`${{ github.repository }}`** has been safely deployed by **`${{ github.actor }}`**.'

    - name: Discord Notification (The job has failed)
      if: ${{ failure() }}
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: ':red_circle: Deployment **failed** for project **`${{ github.repository }}`**. Old version is still active. CC: **`${{ github.actor }}`**.'
