name: farida

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest

    outputs:
      build_path: dist/e-learning/browser

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'

    - name: Install Dependencies
      run: npm install --force

    - name: Build Angular App
      run: npm run build

    - name: Create .htaccess
      run: |
        echo "RewriteEngine On" > dist/e-learning/browser/.htaccess
        echo "RewriteBase /" >> dist/e-learning/browser/.htaccess
        echo "RewriteRule ^index\.html$ - [L]" >> dist/e-learning/browser/.htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-f" >> dist/e-learning/browser/.htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-d" >> dist/e-learning/browser/.htaccess
        echo "RewriteRule . index.html [L]" >> dist/e-learning/browser/.htaccess

  deploy:
    name: Deploy to ${{ matrix.name }}
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: steps-node-1
            host_secret: SSH_HOST_NODE_1
          - name: steps-node-2
            host_secret: SSH_HOST_NODE_2
          - name: steps-node-3
            host_secret: SSH_HOST_NODE_3
          - name: steps-node-4
            host_secret: SSH_HOST_NODE_4

    steps:
    - uses: actions/checkout@v4

    - name: Set Host IP from secret
      id: get_host
      run: echo "host_ip=${{ secrets[matrix.host_secret] }}" >> $GITHUB_OUTPUT

    - name: Upload to temporary folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ steps.get_host.outputs.host_ip }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "dist/e-learning/browser/*"
        target: "/var/www/html/steps-front-deploying"

    - name: Finalize deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.get_host.outputs.host_ip }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mv /var/www/html/steps-front-deploying/dist/e-learning/browser /var/www/html/steps-front-deployed
          rm -rf /var/www/html/steps-front-deploying
          # Make backup of current app if it exists
          if [ -d "/var/www/html/steps-front" ]; then
            rm -rf /var/www/html/steps-front-backup
            mv /var/www/html/steps-front /var/www/html/steps-front-backup
          fi

          # Move the new build into place
          mv /var/www/html/steps-front-deployed /var/www/html/steps-front

    - name: Discord Notification (The job has failed)
      if: ${{ failure() }}
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: ':red_circle: Deployment **failed** to **`${{ matrix.name }}`**. CC: **`${{ github.actor }}`**.'
